export const START_PROCCESS_CART = "START_PROCCESS_CART";
export const END_PROCCESS_CART = "END_PROCCESS_CART";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";
export const INCREASE_ITEM_COUNT = "INCREASE_ITEM_COUNT";
export const DECRESE_ITEM_COUNT = "DECRESE_ITEM_COUNT";
export const CLEAE_CART = "CLEAE_CART";
