export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const DONE_ORDER = "DONE_ORDER";
export const END_PROCCESS_ORDER = "END_PROCCESS_ORDER";
export const START_PROCCESS_ORDER = "START_PROCCESS_ORDER";
