export const START_PROCCESS_PRODUCT = "START_PROCCESS_PRODUCT";
export const END_PROCCESS_PRODUCT = "END_PROCCESS_PRODUCT";
export const SET_ALL_PRODUCTS = "SIGN _OUT_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_DATA_FAIL_PRODUCT = "GET_DATA_FAIL_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_IN_CART = "PRODUCT_IN_CART";
export const PRODUCT_OUT_CART = "PRODUCT_OUT_CAR";
