export const ADD_REVIEWS = "ADD_REVIEWS";
export const START_PROCCESS_REVIEWS = "START_PROCCESS_REVIEWS";
export const END_PROCCESS_REVIEWS = "END_PROCCESS_REVIEWS";
export const GET_ALL_REVIEWS = "GET_ALL_REVIEWS";
